---

version: "3"
volumes:
  data-argus: {}
services:
  argus:
    image: deveshmanish/argus:debian-pip
    container_name: argus
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./config:/var/argus/config
      - ./bin:/opt/argus/
      - ./configDir:/opt/argus/configDir
      - ./users:/var/argus/users
      - data-argus:/var/argus/
    healthcheck:
      test: [ "CMD-SHELL", "argusctl status" ]
      interval: 10s
      timeout: 30s
      retries: 3
